#ifndef SAMPLER_BINDINGS
#define SAMPLER_BINDINGS

#define DIFFUSE_TEXTURE_TEXTURE_UNIT 0
#define SHADOWMAP_TEXTURE_UNIT 2
#define DIRECTIONAL_LIGHTS_SHADOWMAP_TEXTURE_UNIT 3
#define POINT_LIGHTS_SHADOWMAP_TEXTURE_UNIT 4

#endif
