#pragma once
#define GLM_ENABLE_EXPERIMENTAL
#include <utility>
#include <typeinfo>
#include <vector>
#include <string>
#include <memory>
#include <iostream>
#include <functional>
#include <algorithm>
#include <map>
#include "glad/glad.h"
#include "glm/gtx/string_cast.hpp"
#include "glm/glm.hpp"
#include "glm/gtc/quaternion.hpp"
#include "glm/gtx/quaternion.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "uniformBlockBindings.vert"
#include "uniformLocations.vert"
#include "stb_image.h"

using std::string;
using std::vector;
using std::map;
using std::cout;
using std::endl;